# Adds namespace to all resources.
namespace: {NAMESPACE}

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base/
  - traefik.yml

patchesStrategicMerge:
  - configmap.yaml

configMapGenerator:
- name: {APPNAME}-configmap
  files:
  - application.yml
